### PR TITLE
Parameter processing, removed duplicated code

### PR DESCRIPTION
**Pull request by sslb**
Hi,

Appreciate the merge!

One more small fix. I generalised parameter processing and it allowed me to remove some duplicated code and reduce the number of code paths.

I commented the code and hopefully this will help future changes to be single touch-point (say we implement RAML 1.0).

Thanks!

### CODE REVIEW

**Comment by esh-b** [comment]
@sslb , thanks. And are you sure about the correctness of the program? No runtime exceptions or some other kind of errors?

**Comment by sslb** [comment]
Yes, I've tested it. Function passing is actually compile time, no additional runtime exception will happen. The compiler will resolve function references and turn them into standard calls.

**Comment by sslb** [comment]
Thinking about this, you have an absolutely fair point which is tests. I'll write some unit tests for the project if you don't mind and I'll raise a PR later for that. We should be able to isolate various code-paths and test them individually.

**Comment by esh-b** [comment]
Cool..I would embrace it..

**Pull request merged**
